// Extracts the slice of Pokémon Showdown data this game uses (via @pkmn/dex, MIT) into a small
// module, so the 50 MB data package never ships to the browser.
// Run: npm run gen:dex   (after adding a Pokémon to roster.js or a move to moves.js)

import { writeFileSync } from 'node:fs';
import { Dex } from '@pkmn/dex';
import { ROSTER } from '../src/data/roster.js';
import { SPECIALS } from '../src/data/moves.js';

const species = {};
const learnsets = {};
for (const id of Object.keys(ROSTER)) {
  const s = Dex.species.get(id);
  if (!s.exists) throw new Error(`Unknown species ${id}`);
  species[id] = { name: s.name, types: s.types, baseStats: s.baseStats, weightkg: s.weightkg, num: s.num };
  // Which of our implemented moves this species can legally learn (for the team builder).
  const ls = await Dex.learnsets.get(id);
  const legal = new Set(Object.keys(ls.learnset || {}));
  let prevo = s.prevo ? Dex.species.get(s.prevo) : null;
  while (prevo) {
    const pl = await Dex.learnsets.get(prevo.id);
    for (const m of Object.keys(pl.learnset || {})) legal.add(m);
    prevo = prevo.prevo ? Dex.species.get(prevo.prevo) : null;
  }
  learnsets[id] = Object.keys(SPECIALS).filter((m) => legal.has(m));
  for (const m of Object.values(ROSTER[id].moves)) {
    if (!legal.has(m)) throw new Error(`${s.name} cannot learn ${m}`);
  }
}

const moves = {};
for (const id of Object.keys(SPECIALS)) {
  const m = Dex.moves.get(id);
  if (!m.exists) throw new Error(`Unknown move ${id}`);
  moves[id] = {
    name: m.name, type: m.type, cat: m.category.toLowerCase(), power: m.basePower, pp: m.pp,
    priority: m.priority, powder: !!m.flags.powder, contact: !!m.flags.contact,
    desc: m.shortDesc,
  };
}

// typechart[attacking][defending] = Showdown multiplier (2, 1, 0.5 or 0)
const typechart = {};
const types = Dex.types.all().map((t) => t.name).filter((t) => t !== 'Stellar');
for (const atk of types) {
  typechart[atk] = {};
  for (const def of types) {
    const code = Dex.types.get(def).damageTaken[atk];
    typechart[atk][def] = [1, 2, 0.5, 0][code] ?? 1;
  }
}

const out = `// GENERATED by scripts/gen-dex.mjs from Pokémon Showdown data (@pkmn/dex, MIT). Do not edit.
export const DEX = ${JSON.stringify({ species, moves, typechart, learnsets }, null, 1)};
`;
writeFileSync(new URL('../src/data/dex.js', import.meta.url), out);
console.log(`dex.js: ${Object.keys(species).length} species, ${Object.keys(moves).length} moves, ${types.length} types`);
console.log(learnsets);
